//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitOPS_net.SafetyOfficer
{
    public partial class Drivers
    {
        protected global::System.Web.UI.WebControls.Button btnExport;
        protected global::System.Web.UI.WebControls.Button btnAddDriver;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Label lblOnTrip;
        protected global::System.Web.UI.WebControls.Label lblOnTripPct;
        protected global::System.Web.UI.WebControls.Label lblAvailable;
        protected global::System.Web.UI.WebControls.Label lblAvgSafety;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Label lblCount;
        protected global::System.Web.UI.WebControls.GridView gvDrivers;
        protected global::System.Web.UI.WebControls.Label lblEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlDetails;
        protected global::System.Web.UI.WebControls.Label lblDInitials;
        protected global::System.Web.UI.WebControls.Label lblDName;
        protected global::System.Web.UI.WebControls.Label lblDCat;
        protected global::System.Web.UI.WebControls.Label lblDLicense;
        protected global::System.Web.UI.WebControls.Label lblDStatus;
        protected global::System.Web.UI.WebControls.Label lblDScore;
        protected global::System.Web.UI.WebControls.Label lblDExpiry;
        protected global::System.Web.UI.WebControls.Label lblDContact;
        protected global::System.Web.UI.WebControls.Button btnCloseDetails;
        protected global::System.Web.UI.WebControls.Panel pnlAdd;
        protected global::System.Web.UI.WebControls.Label lblFormTitle;
        protected global::System.Web.UI.WebControls.Button btnCloseAdd;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.TextBox txtLicense;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewCat;
        protected global::System.Web.UI.WebControls.TextBox txtContact;
        protected global::System.Web.UI.WebControls.TextBox txtExpiry;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewStatus;
        protected global::System.Web.UI.WebControls.TextBox txtScore;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
