//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitOPS_net.FleetManager
{
    public partial class Vehicles
    {
        protected global::System.Web.UI.WebControls.Button btnAddVehicle;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Label lblOnTrip;
        protected global::System.Web.UI.WebControls.Label lblInShop;
        protected global::System.Web.UI.WebControls.Label lblAvailable;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlType;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Label lblCount;
        protected global::System.Web.UI.WebControls.GridView gvVehicles;
        protected global::System.Web.UI.WebControls.Label lblEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlDetails;
        protected global::System.Web.UI.WebControls.Label lblDReg;
        protected global::System.Web.UI.WebControls.Label lblDName;
        protected global::System.Web.UI.WebControls.Label lblDType;
        protected global::System.Web.UI.WebControls.Label lblDStatus;
        protected global::System.Web.UI.WebControls.Label lblDOdo;
        protected global::System.Web.UI.WebControls.Label lblDLoad;
        protected global::System.Web.UI.WebControls.Label lblDCost;
        protected global::System.Web.UI.WebControls.Button btnCloseDetails;
        protected global::System.Web.UI.WebControls.Panel pnlAdd;
        protected global::System.Web.UI.WebControls.Button btnCloseAdd;
        protected global::System.Web.UI.WebControls.TextBox txtReg;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewType;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewStatus;
        protected global::System.Web.UI.WebControls.TextBox txtLoad;
        protected global::System.Web.UI.WebControls.TextBox txtOdo;
        protected global::System.Web.UI.WebControls.TextBox txtCost;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
