//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitOPS_net.Admin
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Label lblActiveVehicles;
        protected global::System.Web.UI.WebControls.Label lblAvailableVehicles;
        protected global::System.Web.UI.WebControls.Label lblMaintenance;
        protected global::System.Web.UI.WebControls.Label lblActiveTrips;
        protected global::System.Web.UI.WebControls.Label lblPendingTrips;
        protected global::System.Web.UI.WebControls.Label lblDriversDuty;
        protected global::System.Web.UI.WebControls.Label lblUtilization;
        protected global::System.Web.UI.WebControls.GridView gvRecentTrips;
    }
}
