//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitOPS_net.FinancialAnalyst
{
    public partial class FuelExpenses
    {
        protected global::System.Web.UI.WebControls.Button btnFuel;
        protected global::System.Web.UI.WebControls.Button btnExpense;
        protected global::System.Web.UI.WebControls.DropDownList ddlInspect;
        protected global::System.Web.UI.WebControls.Panel pnlCost;
        protected global::System.Web.UI.WebControls.Label lblFuelSum;
        protected global::System.Web.UI.WebControls.Label lblExpSum;
        protected global::System.Web.UI.WebControls.Label lblTotalCost;
        protected global::System.Web.UI.WebControls.GridView gvExpenses;
        protected global::System.Web.UI.WebControls.Label lblEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlFuel;
        protected global::System.Web.UI.WebControls.Button btnCloseFuel;
        protected global::System.Web.UI.WebControls.DropDownList ddlFuelVehicle;
        protected global::System.Web.UI.WebControls.TextBox txtLiters;
        protected global::System.Web.UI.WebControls.TextBox txtFuelCost;
        protected global::System.Web.UI.WebControls.Button btnCancelFuel;
        protected global::System.Web.UI.WebControls.Button btnSaveFuel;
        protected global::System.Web.UI.WebControls.Panel pnlExpense;
        protected global::System.Web.UI.WebControls.Button btnCloseExpense;
        protected global::System.Web.UI.WebControls.DropDownList ddlExpVehicle;
        protected global::System.Web.UI.WebControls.TextBox txtAmount;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.TextBox txtDesc;
        protected global::System.Web.UI.WebControls.Button btnCancelExpense;
        protected global::System.Web.UI.WebControls.Button btnSaveExpense;
    }
}
