//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitOPS_net.Dispatcher
{
    public partial class Trips
    {
        protected global::System.Web.UI.WebControls.Button btnNewTrip;
        protected global::System.Web.UI.WebControls.GridView gvTrips;
        protected global::System.Web.UI.WebControls.Label lblEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlNew;
        protected global::System.Web.UI.WebControls.Button btnCloseNew;
        protected global::System.Web.UI.WebControls.TextBox txtSource;
        protected global::System.Web.UI.WebControls.TextBox txtDest;
        protected global::System.Web.UI.WebControls.TextBox txtCargo;
        protected global::System.Web.UI.WebControls.TextBox txtDist;
        protected global::System.Web.UI.WebControls.DropDownList ddlVehicle;
        protected global::System.Web.UI.WebControls.DropDownList ddlDriver;
        protected global::System.Web.UI.WebControls.Button btnCancelNew;
        protected global::System.Web.UI.WebControls.Button btnCreate;
        protected global::System.Web.UI.WebControls.Panel pnlComplete;
        protected global::System.Web.UI.WebControls.Button btnCloseComplete;
        protected global::System.Web.UI.WebControls.HiddenField hfTrip;
        protected global::System.Web.UI.WebControls.TextBox txtActualKm;
        protected global::System.Web.UI.WebControls.TextBox txtFuel;
        protected global::System.Web.UI.WebControls.Button btnCancelComplete;
        protected global::System.Web.UI.WebControls.Button btnDoComplete;
    }
}
